slam_toolbox:
  ros__parameters:
    # Frames / I/O
    odom_frame: robot/odom
    map_frame: robot/map
    base_frame: robot/base_link
    scan_topic: /scan_merged

    # Mode
    mode: mapping  # mapping | localization | offline

    # TF + map publish
    transform_timeout: 0.2
    transform_publish_period: 0.05
    map_update_interval: 1.0

    # Map rasterization
    resolution: 0.05
    min_laser_range: 0.02
    max_laser_range: 3.5
    minimum_time_interval: 0.1   # sync mode only

    # Matcher / keyframe gating
    minimum_travel_distance: 0.5
    minimum_travel_heading: 0.5
    scan_buffer_size: 10
    scan_buffer_maximum_scan_distance: 10.0
    link_match_minimum_response_fine: 0.8
    link_scan_maximum_distance: 1.5

    # Loop closure
    do_loop_closing: true
    loop_search_maximum_distance: 3.0
    loop_search_space_dimension: 8.0
    loop_search_space_resolution: 0.10
    loop_match_minimum_chain_size: 3
    loop_match_maximum_variance_coarse: 3.0
    loop_match_minimum_response_coarse: 0.5
    loop_match_minimum_response_fine: 0.6

    # Solver (Ceres) â€“ names/values OK
    solver_plugin: solver_plugins::CeresSolver
    ceres_linear_solver: SPARSE_NORMAL_CHOLESKY
    ceres_preconditioner: SCHUR_JACOBI
    ceres_trust_strategy: LEVENBERG_MARQUARDT
    ceres_dogleg_type: TRADITIONAL_DOGLEG
    ceres_loss_function: HuberLoss

    # Misc
    debug_logging: false
    throttle_scans: 1
    enable_interactive_mode: false
